# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created: Wed Jun 19 16:44:40 2013
#      by: pyside-uic 0.2.14 running on PySide 1.1.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(852, 677)
        MainWindow.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.centralwidget = QtGui.QWidget(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.outerSplitter = QtGui.QSplitter(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.outerSplitter.sizePolicy().hasHeightForWidth())
        self.outerSplitter.setSizePolicy(sizePolicy)
        self.outerSplitter.setOrientation(QtCore.Qt.Vertical)
        self.outerSplitter.setObjectName("outerSplitter")
        self.pageSelectorSplitter = QtGui.QSplitter(self.outerSplitter)
        self.pageSelectorSplitter.setOrientation(QtCore.Qt.Horizontal)
        self.pageSelectorSplitter.setObjectName("pageSelectorSplitter")
        self.pageSelector = QtGui.QListWidget(self.pageSelectorSplitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pageSelector.sizePolicy().hasHeightForWidth())
        self.pageSelector.setSizePolicy(sizePolicy)
        self.pageSelector.setMaximumSize(QtCore.QSize(200, 16777215))
        self.pageSelector.setObjectName("pageSelector")
        QtGui.QListWidgetItem(self.pageSelector)
        QtGui.QListWidgetItem(self.pageSelector)
        QtGui.QListWidgetItem(self.pageSelector)
        QtGui.QListWidgetItem(self.pageSelector)
        QtGui.QListWidgetItem(self.pageSelector)
        QtGui.QListWidgetItem(self.pageSelector)
        QtGui.QListWidgetItem(self.pageSelector)
        self.pages = QtGui.QStackedWidget(self.pageSelectorSplitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pages.sizePolicy().hasHeightForWidth())
        self.pages.setSizePolicy(sizePolicy)
        self.pages.setMinimumSize(QtCore.QSize(400, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pages.setFont(font)
        self.pages.setObjectName("pages")
        self.connectionsPage = QtGui.QWidget()
        self.connectionsPage.setObjectName("connectionsPage")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.connectionsPage)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.connectionsLabel = QtGui.QLabel(self.connectionsPage)
        self.connectionsLabel.setObjectName("connectionsLabel")
        self.verticalLayout_4.addWidget(self.connectionsLabel)
        self.connectionsText = QtGui.QPlainTextEdit(self.connectionsPage)
        font = QtGui.QFont()
        font.setFamily("Lucida Console")
        self.connectionsText.setFont(font)
        self.connectionsText.setReadOnly(True)
        self.connectionsText.setObjectName("connectionsText")
        self.verticalLayout_4.addWidget(self.connectionsText)
        self.pages.addWidget(self.connectionsPage)
        self.convergedStatePage = QtGui.QWidget()
        self.convergedStatePage.setObjectName("convergedStatePage")
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.convergedStatePage)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.congergedStateLabel = QtGui.QLabel(self.convergedStatePage)
        self.congergedStateLabel.setObjectName("congergedStateLabel")
        self.verticalLayout_7.addWidget(self.congergedStateLabel)
        self.convergedStateText = QtGui.QPlainTextEdit(self.convergedStatePage)
        font = QtGui.QFont()
        font.setFamily("Lucida Console")
        font.setPointSize(12)
        self.convergedStateText.setFont(font)
        self.convergedStateText.setReadOnly(True)
        self.convergedStateText.setObjectName("convergedStateText")
        self.verticalLayout_7.addWidget(self.convergedStateText)
        self.pages.addWidget(self.convergedStatePage)
        self.instrumentsPage = QtGui.QWidget()
        self.instrumentsPage.setObjectName("instrumentsPage")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.instrumentsPage)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.instrumentsLabel = QtGui.QLabel(self.instrumentsPage)
        self.instrumentsLabel.setObjectName("instrumentsLabel")
        self.verticalLayout_2.addWidget(self.instrumentsLabel)
        self.instrumentsText = QtGui.QPlainTextEdit(self.instrumentsPage)
        font = QtGui.QFont()
        font.setFamily("Lucida Console")
        self.instrumentsText.setFont(font)
        self.instrumentsText.setReadOnly(True)
        self.instrumentsText.setObjectName("instrumentsText")
        self.verticalLayout_2.addWidget(self.instrumentsText)
        self.pages.addWidget(self.instrumentsPage)
        self.parametersPage = QtGui.QWidget()
        self.parametersPage.setObjectName("parametersPage")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.parametersPage)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.scrollArea = QtGui.QScrollArea(self.parametersPage)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.parametersArea = QtGui.QWidget()
        self.parametersArea.setGeometry(QtCore.QRect(0, 0, 595, 349))
        self.parametersArea.setObjectName("parametersArea")
        self.scrollArea.setWidget(self.parametersArea)
        self.verticalLayout_3.addWidget(self.scrollArea)
        self.pages.addWidget(self.parametersPage)
        self.settingsPage = QtGui.QWidget()
        self.settingsPage.setObjectName("settingsPage")
        self.formLayout = QtGui.QFormLayout(self.settingsPage)
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.FieldsStayAtSizeHint)
        self.formLayout.setObjectName("formLayout")
        self.frame = QtGui.QFrame(self.settingsPage)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QtCore.QSize(20, 100))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.formLayout_2 = QtGui.QFormLayout(self.frame)
        self.formLayout_2.setObjectName("formLayout_2")
        self.settingsFileLabel = QtGui.QLabel(self.frame)
        self.settingsFileLabel.setObjectName("settingsFileLabel")
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.settingsFileLabel)
        self.settingsText = QtGui.QPlainTextEdit(self.frame)
        font = QtGui.QFont()
        font.setFamily("Lucida Console")
        font.setPointSize(11)
        self.settingsText.setFont(font)
        self.settingsText.setObjectName("settingsText")
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.SpanningRole, self.settingsText)
        self.settingsFileContainer = QtGui.QWidget(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.settingsFileContainer.sizePolicy().hasHeightForWidth())
        self.settingsFileContainer.setSizePolicy(sizePolicy)
        self.settingsFileContainer.setMinimumSize(QtCore.QSize(50, 0))
        self.settingsFileContainer.setObjectName("settingsFileContainer")
        self.horizontalLayout = QtGui.QHBoxLayout(self.settingsFileContainer)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.settingsFile = QtGui.QLineEdit(self.settingsFileContainer)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.settingsFile.sizePolicy().hasHeightForWidth())
        self.settingsFile.setSizePolicy(sizePolicy)
        self.settingsFile.setMinimumSize(QtCore.QSize(0, 22))
        self.settingsFile.setReadOnly(True)
        self.settingsFile.setObjectName("settingsFile")
        self.horizontalLayout.addWidget(self.settingsFile)
        self.saveSettingsButton = QtGui.QPushButton(self.settingsFileContainer)
        self.saveSettingsButton.setObjectName("saveSettingsButton")
        self.horizontalLayout.addWidget(self.saveSettingsButton)
        self.reloadSettingsButton = QtGui.QPushButton(self.settingsFileContainer)
        self.reloadSettingsButton.setObjectName("reloadSettingsButton")
        self.horizontalLayout.addWidget(self.reloadSettingsButton)
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.settingsFileContainer)
        self.formLayout.setWidget(0, QtGui.QFormLayout.SpanningRole, self.frame)
        self.ipAddressLabel = QtGui.QLabel(self.settingsPage)
        self.ipAddressLabel.setObjectName("ipAddressLabel")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.ipAddressLabel)
        self.ipAddress = QtGui.QLineEdit(self.settingsPage)
        self.ipAddress.setReadOnly(True)
        self.ipAddress.setObjectName("ipAddress")
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.ipAddress)
        self.logIncomingMessagesCheckbox = QtGui.QCheckBox(self.settingsPage)
        self.logIncomingMessagesCheckbox.setObjectName("logIncomingMessagesCheckbox")
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.logIncomingMessagesCheckbox)
        self.logOutgoingMessagesCheckbox = QtGui.QCheckBox(self.settingsPage)
        self.logOutgoingMessagesCheckbox.setObjectName("logOutgoingMessagesCheckbox")
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.logOutgoingMessagesCheckbox)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.formLayout.setItem(4, QtGui.QFormLayout.FieldRole, spacerItem)
        self.pages.addWidget(self.settingsPage)
        self.visualizerPage = QtGui.QWidget()
        self.visualizerPage.setObjectName("visualizerPage")
        self.visualizerPageScrollArea = QtGui.QScrollArea(self.visualizerPage)
        self.visualizerPageScrollArea.setGeometry(QtCore.QRect(0, 0, 631, 360))
        self.visualizerPageScrollArea.setFrameShape(QtGui.QFrame.NoFrame)
        self.visualizerPageScrollArea.setWidgetResizable(True)
        self.visualizerPageScrollArea.setObjectName("visualizerPageScrollArea")
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 616, 370))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollAreaWidgetContents.sizePolicy().hasHeightForWidth())
        self.scrollAreaWidgetContents.setSizePolicy(sizePolicy)
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout = QtGui.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout.setObjectName("gridLayout")
        self.visualizerAddressLabel = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.visualizerAddressLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.visualizerAddressLabel.setObjectName("visualizerAddressLabel")
        self.gridLayout.addWidget(self.visualizerAddressLabel, 0, 0, 1, 1)
        self.visualizerAddress = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.visualizerAddress.setEnabled(False)
        self.visualizerAddress.setReadOnly(True)
        self.visualizerAddress.setObjectName("visualizerAddress")
        self.gridLayout.addWidget(self.visualizerAddress, 0, 1, 1, 1)
        self.visualizerOverviewLabel = QtGui.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.visualizerOverviewLabel.setFont(font)
        self.visualizerOverviewLabel.setObjectName("visualizerOverviewLabel")
        self.gridLayout.addWidget(self.visualizerOverviewLabel, 1, 0, 1, 2)
        self.verticalLayout_9 = QtGui.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.visualizerCanonicalOrderLabel = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.visualizerCanonicalOrderLabel.setObjectName("visualizerCanonicalOrderLabel")
        self.verticalLayout_9.addWidget(self.visualizerCanonicalOrderLabel)
        self.visualizerCanonicalOrder = QtGui.QListView(self.scrollAreaWidgetContents)
        self.visualizerCanonicalOrder.setMinimumSize(QtCore.QSize(150, 150))
        self.visualizerCanonicalOrder.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.visualizerCanonicalOrder.setDragDropMode(QtGui.QAbstractItemView.InternalMove)
        self.visualizerCanonicalOrder.setObjectName("visualizerCanonicalOrder")
        self.verticalLayout_9.addWidget(self.visualizerCanonicalOrder)
        self.gridLayout.addLayout(self.verticalLayout_9, 2, 0, 1, 1)
        self.verticalLayout_8 = QtGui.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.visualizerCalculatedOrderLabel = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.visualizerCalculatedOrderLabel.setObjectName("visualizerCalculatedOrderLabel")
        self.verticalLayout_8.addWidget(self.visualizerCalculatedOrderLabel)
        self.visualizerCalculatedOrder = QtGui.QListView(self.scrollAreaWidgetContents)
        self.visualizerCalculatedOrder.setMinimumSize(QtCore.QSize(150, 0))
        self.visualizerCalculatedOrder.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.visualizerCalculatedOrder.setDragEnabled(False)
        self.visualizerCalculatedOrder.setDragDropMode(QtGui.QAbstractItemView.NoDragDrop)
        self.visualizerCalculatedOrder.setMovement(QtGui.QListView.Static)
        self.visualizerCalculatedOrder.setObjectName("visualizerCalculatedOrder")
        self.verticalLayout_8.addWidget(self.visualizerCalculatedOrder)
        self.gridLayout.addLayout(self.verticalLayout_8, 2, 1, 1, 1)
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.visualizerUnorderedInstrumentsLabel = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.visualizerUnorderedInstrumentsLabel.setObjectName("visualizerUnorderedInstrumentsLabel")
        self.verticalLayout_5.addWidget(self.visualizerUnorderedInstrumentsLabel)
        self.visualizerUnorderedInstruments = QtGui.QListView(self.scrollAreaWidgetContents)
        self.visualizerUnorderedInstruments.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.visualizerUnorderedInstruments.setObjectName("visualizerUnorderedInstruments")
        self.verticalLayout_5.addWidget(self.visualizerUnorderedInstruments)
        self.gridLayout.addLayout(self.verticalLayout_5, 3, 0, 1, 2)
        self.visualizerPageScrollArea.setWidget(self.scrollAreaWidgetContents)
        self.pages.addWidget(self.visualizerPage)
        self.worldStatePage = QtGui.QWidget()
        self.worldStatePage.setObjectName("worldStatePage")
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.worldStatePage)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.worldStateLabel = QtGui.QLabel(self.worldStatePage)
        self.worldStateLabel.setObjectName("worldStateLabel")
        self.verticalLayout_6.addWidget(self.worldStateLabel)
        self.worldStateText = QtGui.QPlainTextEdit(self.worldStatePage)
        font = QtGui.QFont()
        font.setFamily("Lucida Console")
        font.setPointSize(12)
        self.worldStateText.setFont(font)
        self.worldStateText.setReadOnly(True)
        self.worldStateText.setObjectName("worldStateText")
        self.verticalLayout_6.addWidget(self.worldStateText)
        self.pages.addWidget(self.worldStatePage)
        self.layoutWidget = QtGui.QWidget(self.outerSplitter)
        self.layoutWidget.setObjectName("layoutWidget")
        self.lowerSection = QtGui.QVBoxLayout(self.layoutWidget)
        self.lowerSection.setContentsMargins(0, 0, 0, 0)
        self.lowerSection.setObjectName("lowerSection")
        self.logLabel = QtGui.QLabel(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.logLabel.sizePolicy().hasHeightForWidth())
        self.logLabel.setSizePolicy(sizePolicy)
        self.logLabel.setObjectName("logLabel")
        self.lowerSection.addWidget(self.logLabel)
        self.logView = QtGui.QListView(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.logView.sizePolicy().hasHeightForWidth())
        self.logView.setSizePolicy(sizePolicy)
        self.logView.setObjectName("logView")
        self.lowerSection.addWidget(self.logView)
        self.footer = QtGui.QHBoxLayout()
        self.footer.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.footer.setObjectName("footer")
        self.enableInputCheckbox = QtGui.QCheckBox(self.layoutWidget)
        self.enableInputCheckbox.setObjectName("enableInputCheckbox")
        self.footer.addWidget(self.enableInputCheckbox)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.footer.addItem(spacerItem1)
        self.calculateConvergenceCheckbox = QtGui.QCheckBox(self.layoutWidget)
        self.calculateConvergenceCheckbox.setObjectName("calculateConvergenceCheckbox")
        self.footer.addWidget(self.calculateConvergenceCheckbox)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.footer.addItem(spacerItem2)
        self.enableOutputCheckbox = QtGui.QCheckBox(self.layoutWidget)
        self.enableOutputCheckbox.setObjectName("enableOutputCheckbox")
        self.footer.addWidget(self.enableOutputCheckbox)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.footer.addItem(spacerItem3)
        self.lowerSection.addLayout(self.footer)
        self.verticalLayout.addWidget(self.outerSplitter)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar()
        self.menubar.setGeometry(QtCore.QRect(0, 0, 852, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionQuit = QtGui.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionSave_log = QtGui.QAction(MainWindow)
        self.actionSave_log.setObjectName("actionSave_log")
        self.actionSaveSettings = QtGui.QAction(MainWindow)
        self.actionSaveSettings.setShortcutContext(QtCore.Qt.ApplicationShortcut)
        self.actionSaveSettings.setObjectName("actionSaveSettings")
        self.actionOpenSnapshot = QtGui.QAction(MainWindow)
        self.actionOpenSnapshot.setObjectName("actionOpenSnapshot")
        self.actionSaveSnapshotAs = QtGui.QAction(MainWindow)
        self.actionSaveSnapshotAs.setObjectName("actionSaveSnapshotAs")
        self.actionReloadSettings = QtGui.QAction(MainWindow)
        self.actionReloadSettings.setObjectName("actionReloadSettings")
        self.actionSaveSnapshot = QtGui.QAction(MainWindow)
        self.actionSaveSnapshot.setObjectName("actionSaveSnapshot")
        self.menuFile.addAction(self.actionOpenSnapshot)
        self.menuFile.addAction(self.actionReloadSettings)
        self.menuFile.addAction(self.actionSaveSettings)
        self.menuFile.addAction(self.actionSaveSnapshot)
        self.menuFile.addAction(self.actionSaveSnapshotAs)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSave_log)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menubar.addAction(self.menuFile.menuAction())
        self.ipAddressLabel.setBuddy(self.ipAddress)

        self.retranslateUi(MainWindow)
        self.pages.setCurrentIndex(5)
        QtCore.QObject.connect(self.pageSelector, QtCore.SIGNAL("currentRowChanged(int)"), self.pages.setCurrentIndex)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Stabilizer", None, QtGui.QApplication.UnicodeUTF8))
        __sortingEnabled = self.pageSelector.isSortingEnabled()
        self.pageSelector.setSortingEnabled(False)
        self.pageSelector.item(0).setText(QtGui.QApplication.translate("MainWindow", "Connections", None, QtGui.QApplication.UnicodeUTF8))
        self.pageSelector.item(1).setText(QtGui.QApplication.translate("MainWindow", "Converged State", None, QtGui.QApplication.UnicodeUTF8))
        self.pageSelector.item(2).setText(QtGui.QApplication.translate("MainWindow", "Instruments", None, QtGui.QApplication.UnicodeUTF8))
        self.pageSelector.item(3).setText(QtGui.QApplication.translate("MainWindow", "Parameters", None, QtGui.QApplication.UnicodeUTF8))
        self.pageSelector.item(4).setText(QtGui.QApplication.translate("MainWindow", "Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.pageSelector.item(5).setText(QtGui.QApplication.translate("MainWindow", "Visualizer", None, QtGui.QApplication.UnicodeUTF8))
        self.pageSelector.item(6).setText(QtGui.QApplication.translate("MainWindow", "World State", None, QtGui.QApplication.UnicodeUTF8))
        self.pageSelector.setSortingEnabled(__sortingEnabled)
        self.connectionsLabel.setText(QtGui.QApplication.translate("MainWindow", "Currently detected connections", None, QtGui.QApplication.UnicodeUTF8))
        self.congergedStateLabel.setText(QtGui.QApplication.translate("MainWindow", "Converged State", None, QtGui.QApplication.UnicodeUTF8))
        self.instrumentsLabel.setText(QtGui.QApplication.translate("MainWindow", "Currently connected instruments", None, QtGui.QApplication.UnicodeUTF8))
        self.settingsFileLabel.setText(QtGui.QApplication.translate("MainWindow", "Settings file", None, QtGui.QApplication.UnicodeUTF8))
        self.saveSettingsButton.setText(QtGui.QApplication.translate("MainWindow", "&Save", None, QtGui.QApplication.UnicodeUTF8))
        self.reloadSettingsButton.setText(QtGui.QApplication.translate("MainWindow", "&Reload", None, QtGui.QApplication.UnicodeUTF8))
        self.ipAddressLabel.setText(QtGui.QApplication.translate("MainWindow", "IP Address", None, QtGui.QApplication.UnicodeUTF8))
        self.ipAddress.setText(QtGui.QApplication.translate("MainWindow", "127.0.0.1", None, QtGui.QApplication.UnicodeUTF8))
        self.logIncomingMessagesCheckbox.setText(QtGui.QApplication.translate("MainWindow", "Log incoming messages", None, QtGui.QApplication.UnicodeUTF8))
        self.logOutgoingMessagesCheckbox.setText(QtGui.QApplication.translate("MainWindow", "Log outgoing messages", None, QtGui.QApplication.UnicodeUTF8))
        self.visualizerAddressLabel.setText(QtGui.QApplication.translate("MainWindow", "Visualizer Address", None, QtGui.QApplication.UnicodeUTF8))
        self.visualizerOverviewLabel.setText(QtGui.QApplication.translate("MainWindow", "Instrument order for visualization (anti-clockwise)", None, QtGui.QApplication.UnicodeUTF8))
        self.visualizerCanonicalOrderLabel.setText(QtGui.QApplication.translate("MainWindow", "Canonical order (persistent)", None, QtGui.QApplication.UnicodeUTF8))
        self.visualizerCalculatedOrderLabel.setText(QtGui.QApplication.translate("MainWindow", "Calculated order based on current instruments", None, QtGui.QApplication.UnicodeUTF8))
        self.visualizerUnorderedInstrumentsLabel.setText(QtGui.QApplication.translate("MainWindow", "Unordered instruments (double click to add)", None, QtGui.QApplication.UnicodeUTF8))
        self.worldStateLabel.setText(QtGui.QApplication.translate("MainWindow", "World State", None, QtGui.QApplication.UnicodeUTF8))
        self.logLabel.setText(QtGui.QApplication.translate("MainWindow", "Log", None, QtGui.QApplication.UnicodeUTF8))
        self.enableInputCheckbox.setText(QtGui.QApplication.translate("MainWindow", "Listen for input", None, QtGui.QApplication.UnicodeUTF8))
        self.calculateConvergenceCheckbox.setText(QtGui.QApplication.translate("MainWindow", "Calculate convergence", None, QtGui.QApplication.UnicodeUTF8))
        self.enableOutputCheckbox.setText(QtGui.QApplication.translate("MainWindow", "Send output", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit.setText(QtGui.QApplication.translate("MainWindow", "Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave_log.setText(QtGui.QApplication.translate("MainWindow", "Save log", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSaveSettings.setText(QtGui.QApplication.translate("MainWindow", "&Save settings", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSaveSettings.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+S", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpenSnapshot.setText(QtGui.QApplication.translate("MainWindow", "&Open settings snapshot...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpenSnapshot.setToolTip(QtGui.QApplication.translate("MainWindow", "Open snapshot", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSaveSnapshotAs.setText(QtGui.QApplication.translate("MainWindow", "&Save settings snapshot as...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSaveSnapshotAs.setToolTip(QtGui.QApplication.translate("MainWindow", "Save snapshot as...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionReloadSettings.setText(QtGui.QApplication.translate("MainWindow", "&Reload settings", None, QtGui.QApplication.UnicodeUTF8))
        self.actionReloadSettings.setToolTip(QtGui.QApplication.translate("MainWindow", "Reload settings", None, QtGui.QApplication.UnicodeUTF8))
        self.actionReloadSettings.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+R", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSaveSnapshot.setText(QtGui.QApplication.translate("MainWindow", "Save settings snapshot", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSaveSnapshot.setToolTip(QtGui.QApplication.translate("MainWindow", "Save snapshot", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSaveSnapshot.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Alt+S", None, QtGui.QApplication.UnicodeUTF8))

