# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created: Thu May 23 21:13:55 2013
#      by: pyside-uic 0.2.14 running on PySide 1.1.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(852, 677)
        MainWindow.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.centralwidget = QtGui.QWidget(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.outerSplitter = QtGui.QSplitter(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.outerSplitter.sizePolicy().hasHeightForWidth())
        self.outerSplitter.setSizePolicy(sizePolicy)
        self.outerSplitter.setOrientation(QtCore.Qt.Vertical)
        self.outerSplitter.setObjectName("outerSplitter")
        self.pageSelectorSplitter = QtGui.QSplitter(self.outerSplitter)
        self.pageSelectorSplitter.setOrientation(QtCore.Qt.Horizontal)
        self.pageSelectorSplitter.setObjectName("pageSelectorSplitter")
        self.pageSelector = QtGui.QListWidget(self.pageSelectorSplitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pageSelector.sizePolicy().hasHeightForWidth())
        self.pageSelector.setSizePolicy(sizePolicy)
        self.pageSelector.setMaximumSize(QtCore.QSize(200, 16777215))
        self.pageSelector.setObjectName("pageSelector")
        QtGui.QListWidgetItem(self.pageSelector)
        QtGui.QListWidgetItem(self.pageSelector)
        QtGui.QListWidgetItem(self.pageSelector)
        QtGui.QListWidgetItem(self.pageSelector)
        QtGui.QListWidgetItem(self.pageSelector)
        QtGui.QListWidgetItem(self.pageSelector)
        self.pages = QtGui.QStackedWidget(self.pageSelectorSplitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pages.sizePolicy().hasHeightForWidth())
        self.pages.setSizePolicy(sizePolicy)
        self.pages.setMinimumSize(QtCore.QSize(400, 0))
        self.pages.setObjectName("pages")
        self.connectionsPage = QtGui.QWidget()
        self.connectionsPage.setObjectName("connectionsPage")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.connectionsPage)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.connectionsLabel = QtGui.QLabel(self.connectionsPage)
        self.connectionsLabel.setObjectName("connectionsLabel")
        self.verticalLayout_4.addWidget(self.connectionsLabel)
        self.connectionsText = QtGui.QPlainTextEdit(self.connectionsPage)
        font = QtGui.QFont()
        font.setFamily("Lucida Console")
        self.connectionsText.setFont(font)
        self.connectionsText.setReadOnly(True)
        self.connectionsText.setObjectName("connectionsText")
        self.verticalLayout_4.addWidget(self.connectionsText)
        self.pages.addWidget(self.connectionsPage)
        self.convergedStatePage = QtGui.QWidget()
        self.convergedStatePage.setObjectName("convergedStatePage")
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.convergedStatePage)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.congergedStateLabel = QtGui.QLabel(self.convergedStatePage)
        self.congergedStateLabel.setObjectName("congergedStateLabel")
        self.verticalLayout_7.addWidget(self.congergedStateLabel)
        self.convergedStateText = QtGui.QPlainTextEdit(self.convergedStatePage)
        font = QtGui.QFont()
        font.setFamily("Lucida Console")
        font.setPointSize(12)
        self.convergedStateText.setFont(font)
        self.convergedStateText.setReadOnly(True)
        self.convergedStateText.setObjectName("convergedStateText")
        self.verticalLayout_7.addWidget(self.convergedStateText)
        self.pages.addWidget(self.convergedStatePage)
        self.instrumentsPage = QtGui.QWidget()
        self.instrumentsPage.setObjectName("instrumentsPage")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.instrumentsPage)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.instrumentsLabel = QtGui.QLabel(self.instrumentsPage)
        self.instrumentsLabel.setObjectName("instrumentsLabel")
        self.verticalLayout_2.addWidget(self.instrumentsLabel)
        self.instrumentsText = QtGui.QPlainTextEdit(self.instrumentsPage)
        font = QtGui.QFont()
        font.setFamily("Lucida Console")
        self.instrumentsText.setFont(font)
        self.instrumentsText.setReadOnly(True)
        self.instrumentsText.setObjectName("instrumentsText")
        self.verticalLayout_2.addWidget(self.instrumentsText)
        self.pages.addWidget(self.instrumentsPage)
        self.parametersPage = QtGui.QWidget()
        self.parametersPage.setObjectName("parametersPage")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.parametersPage)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.parametersLabel = QtGui.QLabel(self.parametersPage)
        self.parametersLabel.setObjectName("parametersLabel")
        self.verticalLayout_3.addWidget(self.parametersLabel)
        self.scrollArea = QtGui.QScrollArea(self.parametersPage)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.parametersArea = QtGui.QWidget()
        self.parametersArea.setGeometry(QtCore.QRect(0, 0, 595, 348))
        self.parametersArea.setObjectName("parametersArea")
        self.scrollArea.setWidget(self.parametersArea)
        self.verticalLayout_3.addWidget(self.scrollArea)
        self.pages.addWidget(self.parametersPage)
        self.settingsPage = QtGui.QWidget()
        self.settingsPage.setObjectName("settingsPage")
        self.formLayout = QtGui.QFormLayout(self.settingsPage)
        self.formLayout.setObjectName("formLayout")
        self.settingsFileLabel = QtGui.QLabel(self.settingsPage)
        self.settingsFileLabel.setObjectName("settingsFileLabel")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.settingsFileLabel)
        self.frame = QtGui.QFrame(self.settingsPage)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QtCore.QSize(20, 100))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.frame)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.settingsFile = QtGui.QLineEdit(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.settingsFile.sizePolicy().hasHeightForWidth())
        self.settingsFile.setSizePolicy(sizePolicy)
        self.settingsFile.setMinimumSize(QtCore.QSize(0, 22))
        self.settingsFile.setObjectName("settingsFile")
        self.verticalLayout_5.addWidget(self.settingsFile)
        self.settingsFileButtonsContainerWidget = QtGui.QWidget(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.settingsFileButtonsContainerWidget.sizePolicy().hasHeightForWidth())
        self.settingsFileButtonsContainerWidget.setSizePolicy(sizePolicy)
        self.settingsFileButtonsContainerWidget.setMinimumSize(QtCore.QSize(0, 50))
        self.settingsFileButtonsContainerWidget.setObjectName("settingsFileButtonsContainerWidget")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.settingsFileButtonsContainerWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.reloadSettingsButton = QtGui.QPushButton(self.settingsFileButtonsContainerWidget)
        self.reloadSettingsButton.setObjectName("reloadSettingsButton")
        self.horizontalLayout_2.addWidget(self.reloadSettingsButton)
        self.openSettingsButton = QtGui.QPushButton(self.settingsFileButtonsContainerWidget)
        self.openSettingsButton.setObjectName("openSettingsButton")
        self.horizontalLayout_2.addWidget(self.openSettingsButton)
        self.saveSettingsButton = QtGui.QPushButton(self.settingsFileButtonsContainerWidget)
        self.saveSettingsButton.setObjectName("saveSettingsButton")
        self.horizontalLayout_2.addWidget(self.saveSettingsButton)
        self.saveSettingsAsButton = QtGui.QPushButton(self.settingsFileButtonsContainerWidget)
        self.saveSettingsAsButton.setObjectName("saveSettingsAsButton")
        self.horizontalLayout_2.addWidget(self.saveSettingsAsButton)
        self.verticalLayout_5.addWidget(self.settingsFileButtonsContainerWidget)
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.frame)
        self.ipAddressLabel = QtGui.QLabel(self.settingsPage)
        self.ipAddressLabel.setObjectName("ipAddressLabel")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.ipAddressLabel)
        self.ipAddress = QtGui.QLineEdit(self.settingsPage)
        self.ipAddress.setReadOnly(True)
        self.ipAddress.setObjectName("ipAddress")
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.ipAddress)
        self.pluginsLabel = QtGui.QLabel(self.settingsPage)
        self.pluginsLabel.setObjectName("pluginsLabel")
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.pluginsLabel)
        self.plugins = QtGui.QListView(self.settingsPage)
        self.plugins.setAlternatingRowColors(False)
        self.plugins.setResizeMode(QtGui.QListView.Adjust)
        self.plugins.setObjectName("plugins")
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.plugins)
        self.pushButton = QtGui.QPushButton(self.settingsPage)
        self.pushButton.setObjectName("pushButton")
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.pushButton)
        self.logIncomingMessagesCheckbox = QtGui.QCheckBox(self.settingsPage)
        self.logIncomingMessagesCheckbox.setObjectName("logIncomingMessagesCheckbox")
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.logIncomingMessagesCheckbox)
        self.logOutgoingMessagesCheckbox = QtGui.QCheckBox(self.settingsPage)
        self.logOutgoingMessagesCheckbox.setObjectName("logOutgoingMessagesCheckbox")
        self.formLayout.setWidget(5, QtGui.QFormLayout.FieldRole, self.logOutgoingMessagesCheckbox)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.formLayout.setItem(6, QtGui.QFormLayout.FieldRole, spacerItem)
        self.pages.addWidget(self.settingsPage)
        self.worldStatePage = QtGui.QWidget()
        self.worldStatePage.setObjectName("worldStatePage")
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.worldStatePage)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.worldStateLabel = QtGui.QLabel(self.worldStatePage)
        self.worldStateLabel.setObjectName("worldStateLabel")
        self.verticalLayout_6.addWidget(self.worldStateLabel)
        self.worldStateText = QtGui.QPlainTextEdit(self.worldStatePage)
        font = QtGui.QFont()
        font.setFamily("Lucida Console")
        font.setPointSize(12)
        self.worldStateText.setFont(font)
        self.worldStateText.setReadOnly(True)
        self.worldStateText.setObjectName("worldStateText")
        self.verticalLayout_6.addWidget(self.worldStateText)
        self.pages.addWidget(self.worldStatePage)
        self.layoutWidget = QtGui.QWidget(self.outerSplitter)
        self.layoutWidget.setObjectName("layoutWidget")
        self.lowerSection = QtGui.QVBoxLayout(self.layoutWidget)
        self.lowerSection.setContentsMargins(0, 0, 0, 0)
        self.lowerSection.setObjectName("lowerSection")
        self.logLabel = QtGui.QLabel(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.logLabel.sizePolicy().hasHeightForWidth())
        self.logLabel.setSizePolicy(sizePolicy)
        self.logLabel.setObjectName("logLabel")
        self.lowerSection.addWidget(self.logLabel)
        self.logView = QtGui.QListView(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.logView.sizePolicy().hasHeightForWidth())
        self.logView.setSizePolicy(sizePolicy)
        self.logView.setObjectName("logView")
        self.lowerSection.addWidget(self.logView)
        self.footer = QtGui.QHBoxLayout()
        self.footer.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.footer.setObjectName("footer")
        self.enableInputCheckbox = QtGui.QCheckBox(self.layoutWidget)
        self.enableInputCheckbox.setObjectName("enableInputCheckbox")
        self.footer.addWidget(self.enableInputCheckbox)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.footer.addItem(spacerItem1)
        self.calculateConvergenceCheckbox = QtGui.QCheckBox(self.layoutWidget)
        self.calculateConvergenceCheckbox.setObjectName("calculateConvergenceCheckbox")
        self.footer.addWidget(self.calculateConvergenceCheckbox)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.footer.addItem(spacerItem2)
        self.enableOutputCheckbox = QtGui.QCheckBox(self.layoutWidget)
        self.enableOutputCheckbox.setObjectName("enableOutputCheckbox")
        self.footer.addWidget(self.enableOutputCheckbox)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.footer.addItem(spacerItem3)
        self.lowerSection.addLayout(self.footer)
        self.verticalLayout.addWidget(self.outerSplitter)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar()
        self.menubar.setGeometry(QtCore.QRect(0, 0, 852, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionQuit = QtGui.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionSave_log = QtGui.QAction(MainWindow)
        self.actionSave_log.setObjectName("actionSave_log")
        self.actionSaveSettings = QtGui.QAction(MainWindow)
        self.actionSaveSettings.setShortcutContext(QtCore.Qt.ApplicationShortcut)
        self.actionSaveSettings.setObjectName("actionSaveSettings")
        self.actionOpenSettings = QtGui.QAction(MainWindow)
        self.actionOpenSettings.setObjectName("actionOpenSettings")
        self.actionSaveSettingsAs = QtGui.QAction(MainWindow)
        self.actionSaveSettingsAs.setObjectName("actionSaveSettingsAs")
        self.actionReloadSettings = QtGui.QAction(MainWindow)
        self.actionReloadSettings.setObjectName("actionReloadSettings")
        self.menuFile.addAction(self.actionOpenSettings)
        self.menuFile.addAction(self.actionReloadSettings)
        self.menuFile.addAction(self.actionSaveSettings)
        self.menuFile.addAction(self.actionSaveSettingsAs)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSave_log)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menubar.addAction(self.menuFile.menuAction())
        self.settingsFileLabel.setBuddy(self.settingsFile)
        self.ipAddressLabel.setBuddy(self.ipAddress)
        self.pluginsLabel.setBuddy(self.plugins)

        self.retranslateUi(MainWindow)
        self.pages.setCurrentIndex(3)
        QtCore.QObject.connect(self.pageSelector, QtCore.SIGNAL("currentRowChanged(int)"), self.pages.setCurrentIndex)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Stabilizer", None, QtGui.QApplication.UnicodeUTF8))
        __sortingEnabled = self.pageSelector.isSortingEnabled()
        self.pageSelector.setSortingEnabled(False)
        self.pageSelector.item(0).setText(QtGui.QApplication.translate("MainWindow", "Connections", None, QtGui.QApplication.UnicodeUTF8))
        self.pageSelector.item(1).setText(QtGui.QApplication.translate("MainWindow", "Converged State", None, QtGui.QApplication.UnicodeUTF8))
        self.pageSelector.item(2).setText(QtGui.QApplication.translate("MainWindow", "Instruments", None, QtGui.QApplication.UnicodeUTF8))
        self.pageSelector.item(3).setText(QtGui.QApplication.translate("MainWindow", "Parameters", None, QtGui.QApplication.UnicodeUTF8))
        self.pageSelector.item(4).setText(QtGui.QApplication.translate("MainWindow", "Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.pageSelector.item(5).setText(QtGui.QApplication.translate("MainWindow", "World State", None, QtGui.QApplication.UnicodeUTF8))
        self.pageSelector.setSortingEnabled(__sortingEnabled)
        self.connectionsLabel.setText(QtGui.QApplication.translate("MainWindow", "Currently detected connections", None, QtGui.QApplication.UnicodeUTF8))
        self.congergedStateLabel.setText(QtGui.QApplication.translate("MainWindow", "Converged State", None, QtGui.QApplication.UnicodeUTF8))
        self.instrumentsLabel.setText(QtGui.QApplication.translate("MainWindow", "Currently connected instruments", None, QtGui.QApplication.UnicodeUTF8))
        self.parametersLabel.setText(QtGui.QApplication.translate("MainWindow", "Parameters", None, QtGui.QApplication.UnicodeUTF8))
        self.settingsFileLabel.setText(QtGui.QApplication.translate("MainWindow", "Settings file", None, QtGui.QApplication.UnicodeUTF8))
        self.reloadSettingsButton.setText(QtGui.QApplication.translate("MainWindow", "Reload", None, QtGui.QApplication.UnicodeUTF8))
        self.openSettingsButton.setText(QtGui.QApplication.translate("MainWindow", "&Open...", None, QtGui.QApplication.UnicodeUTF8))
        self.saveSettingsButton.setText(QtGui.QApplication.translate("MainWindow", "&Save", None, QtGui.QApplication.UnicodeUTF8))
        self.saveSettingsAsButton.setText(QtGui.QApplication.translate("MainWindow", "Save &as...", None, QtGui.QApplication.UnicodeUTF8))
        self.ipAddressLabel.setText(QtGui.QApplication.translate("MainWindow", "IP Address", None, QtGui.QApplication.UnicodeUTF8))
        self.ipAddress.setText(QtGui.QApplication.translate("MainWindow", "127.0.0.1", None, QtGui.QApplication.UnicodeUTF8))
        self.pluginsLabel.setText(QtGui.QApplication.translate("MainWindow", "Loaded plugins", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setText(QtGui.QApplication.translate("MainWindow", "Refresh", None, QtGui.QApplication.UnicodeUTF8))
        self.logIncomingMessagesCheckbox.setText(QtGui.QApplication.translate("MainWindow", "Log incoming messages", None, QtGui.QApplication.UnicodeUTF8))
        self.logOutgoingMessagesCheckbox.setText(QtGui.QApplication.translate("MainWindow", "Log outgoing messages", None, QtGui.QApplication.UnicodeUTF8))
        self.worldStateLabel.setText(QtGui.QApplication.translate("MainWindow", "World State", None, QtGui.QApplication.UnicodeUTF8))
        self.logLabel.setText(QtGui.QApplication.translate("MainWindow", "Log", None, QtGui.QApplication.UnicodeUTF8))
        self.enableInputCheckbox.setText(QtGui.QApplication.translate("MainWindow", "Listen for input", None, QtGui.QApplication.UnicodeUTF8))
        self.calculateConvergenceCheckbox.setText(QtGui.QApplication.translate("MainWindow", "Calculate convergence", None, QtGui.QApplication.UnicodeUTF8))
        self.enableOutputCheckbox.setText(QtGui.QApplication.translate("MainWindow", "Send output", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit.setText(QtGui.QApplication.translate("MainWindow", "Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave_log.setText(QtGui.QApplication.translate("MainWindow", "Save log", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSaveSettings.setText(QtGui.QApplication.translate("MainWindow", "&Save settings", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSaveSettings.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+S", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpenSettings.setText(QtGui.QApplication.translate("MainWindow", "&Open...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSaveSettingsAs.setText(QtGui.QApplication.translate("MainWindow", "&Save settings as...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionReloadSettings.setText(QtGui.QApplication.translate("MainWindow", "&Reload", None, QtGui.QApplication.UnicodeUTF8))
        self.actionReloadSettings.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+R", None, QtGui.QApplication.UnicodeUTF8))

