# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created: Sun May 12 19:57:31 2013
#      by: pyside-uic 0.2.14 running on PySide 1.1.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(852, 677)
        MainWindow.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.centralwidget = QtGui.QWidget(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.outerSplitter = QtGui.QSplitter(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.outerSplitter.sizePolicy().hasHeightForWidth())
        self.outerSplitter.setSizePolicy(sizePolicy)
        self.outerSplitter.setOrientation(QtCore.Qt.Vertical)
        self.outerSplitter.setObjectName("outerSplitter")
        self.pageSelectorSplitter = QtGui.QSplitter(self.outerSplitter)
        self.pageSelectorSplitter.setOrientation(QtCore.Qt.Horizontal)
        self.pageSelectorSplitter.setObjectName("pageSelectorSplitter")
        self.pageSelector = QtGui.QListWidget(self.pageSelectorSplitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pageSelector.sizePolicy().hasHeightForWidth())
        self.pageSelector.setSizePolicy(sizePolicy)
        self.pageSelector.setMaximumSize(QtCore.QSize(200, 16777215))
        self.pageSelector.setObjectName("pageSelector")
        QtGui.QListWidgetItem(self.pageSelector)
        QtGui.QListWidgetItem(self.pageSelector)
        QtGui.QListWidgetItem(self.pageSelector)
        QtGui.QListWidgetItem(self.pageSelector)
        self.pages = QtGui.QStackedWidget(self.pageSelectorSplitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pages.sizePolicy().hasHeightForWidth())
        self.pages.setSizePolicy(sizePolicy)
        self.pages.setMinimumSize(QtCore.QSize(400, 0))
        self.pages.setObjectName("pages")
        self.connectionsPage = QtGui.QWidget()
        self.connectionsPage.setObjectName("connectionsPage")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.connectionsPage)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.connectionsLabel = QtGui.QLabel(self.connectionsPage)
        self.connectionsLabel.setObjectName("connectionsLabel")
        self.verticalLayout_4.addWidget(self.connectionsLabel)
        self.connectionsText = QtGui.QPlainTextEdit(self.connectionsPage)
        font = QtGui.QFont()
        font.setFamily("Lucida Console")
        self.connectionsText.setFont(font)
        self.connectionsText.setReadOnly(True)
        self.connectionsText.setObjectName("connectionsText")
        self.verticalLayout_4.addWidget(self.connectionsText)
        self.pages.addWidget(self.connectionsPage)
        self.convergencePage = QtGui.QWidget()
        self.convergencePage.setObjectName("convergencePage")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.convergencePage)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.worldStateLabel = QtGui.QLabel(self.convergencePage)
        self.worldStateLabel.setObjectName("worldStateLabel")
        self.verticalLayout_3.addWidget(self.worldStateLabel)
        self.worldStateText = QtGui.QPlainTextEdit(self.convergencePage)
        font = QtGui.QFont()
        font.setFamily("Lucida Console")
        self.worldStateText.setFont(font)
        self.worldStateText.setReadOnly(True)
        self.worldStateText.setCenterOnScroll(True)
        self.worldStateText.setObjectName("worldStateText")
        self.verticalLayout_3.addWidget(self.worldStateText)
        self.convergedStateLabel = QtGui.QLabel(self.convergencePage)
        self.convergedStateLabel.setObjectName("convergedStateLabel")
        self.verticalLayout_3.addWidget(self.convergedStateLabel)
        self.convergedStateText = QtGui.QPlainTextEdit(self.convergencePage)
        font = QtGui.QFont()
        font.setFamily("Lucida Console")
        self.convergedStateText.setFont(font)
        self.convergedStateText.setReadOnly(True)
        self.convergedStateText.setCenterOnScroll(True)
        self.convergedStateText.setObjectName("convergedStateText")
        self.verticalLayout_3.addWidget(self.convergedStateText)
        self.pages.addWidget(self.convergencePage)
        self.instrumentsPage = QtGui.QWidget()
        self.instrumentsPage.setObjectName("instrumentsPage")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.instrumentsPage)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.instrumentsLabel = QtGui.QLabel(self.instrumentsPage)
        self.instrumentsLabel.setObjectName("instrumentsLabel")
        self.verticalLayout_2.addWidget(self.instrumentsLabel)
        self.instrumentsText = QtGui.QPlainTextEdit(self.instrumentsPage)
        font = QtGui.QFont()
        font.setFamily("Lucida Console")
        self.instrumentsText.setFont(font)
        self.instrumentsText.setReadOnly(True)
        self.instrumentsText.setObjectName("instrumentsText")
        self.verticalLayout_2.addWidget(self.instrumentsText)
        self.pages.addWidget(self.instrumentsPage)
        self.settingsPage = QtGui.QWidget()
        self.settingsPage.setObjectName("settingsPage")
        self.formLayout = QtGui.QFormLayout(self.settingsPage)
        self.formLayout.setObjectName("formLayout")
        self.ipAddressLabel = QtGui.QLabel(self.settingsPage)
        self.ipAddressLabel.setObjectName("ipAddressLabel")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.ipAddressLabel)
        self.ipAddress = QtGui.QLineEdit(self.settingsPage)
        self.ipAddress.setReadOnly(True)
        self.ipAddress.setObjectName("ipAddress")
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.ipAddress)
        self.pluginsLabel = QtGui.QLabel(self.settingsPage)
        self.pluginsLabel.setObjectName("pluginsLabel")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.pluginsLabel)
        self.plugins = QtGui.QListView(self.settingsPage)
        self.plugins.setAlternatingRowColors(False)
        self.plugins.setResizeMode(QtGui.QListView.Adjust)
        self.plugins.setObjectName("plugins")
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.plugins)
        self.pushButton = QtGui.QPushButton(self.settingsPage)
        self.pushButton.setObjectName("pushButton")
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.pushButton)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.formLayout.setItem(5, QtGui.QFormLayout.FieldRole, spacerItem)
        self.logIncomingMessagesCheckbox = QtGui.QCheckBox(self.settingsPage)
        self.logIncomingMessagesCheckbox.setObjectName("logIncomingMessagesCheckbox")
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.logIncomingMessagesCheckbox)
        self.logOutgoingMessagesCheckbox = QtGui.QCheckBox(self.settingsPage)
        self.logOutgoingMessagesCheckbox.setObjectName("logOutgoingMessagesCheckbox")
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.logOutgoingMessagesCheckbox)
        self.pages.addWidget(self.settingsPage)
        self.layoutWidget = QtGui.QWidget(self.outerSplitter)
        self.layoutWidget.setObjectName("layoutWidget")
        self.lowerSection = QtGui.QVBoxLayout(self.layoutWidget)
        self.lowerSection.setContentsMargins(0, 0, 0, 0)
        self.lowerSection.setObjectName("lowerSection")
        self.logLabel = QtGui.QLabel(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.logLabel.sizePolicy().hasHeightForWidth())
        self.logLabel.setSizePolicy(sizePolicy)
        self.logLabel.setObjectName("logLabel")
        self.lowerSection.addWidget(self.logLabel)
        self.logView = QtGui.QListView(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.logView.sizePolicy().hasHeightForWidth())
        self.logView.setSizePolicy(sizePolicy)
        self.logView.setObjectName("logView")
        self.lowerSection.addWidget(self.logView)
        self.footer = QtGui.QHBoxLayout()
        self.footer.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.footer.setObjectName("footer")
        self.enableInputCheckbox = QtGui.QCheckBox(self.layoutWidget)
        self.enableInputCheckbox.setObjectName("enableInputCheckbox")
        self.footer.addWidget(self.enableInputCheckbox)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.footer.addItem(spacerItem1)
        self.calculateConvergenceCheckbox = QtGui.QCheckBox(self.layoutWidget)
        self.calculateConvergenceCheckbox.setObjectName("calculateConvergenceCheckbox")
        self.footer.addWidget(self.calculateConvergenceCheckbox)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.footer.addItem(spacerItem2)
        self.enableOutputCheckbox = QtGui.QCheckBox(self.layoutWidget)
        self.enableOutputCheckbox.setObjectName("enableOutputCheckbox")
        self.footer.addWidget(self.enableOutputCheckbox)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.footer.addItem(spacerItem3)
        self.lowerSection.addLayout(self.footer)
        self.verticalLayout.addWidget(self.outerSplitter)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar()
        self.menubar.setGeometry(QtCore.QRect(0, 0, 852, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionQuit = QtGui.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionSave_log = QtGui.QAction(MainWindow)
        self.actionSave_log.setObjectName("actionSave_log")
        self.menuFile.addAction(self.actionSave_log)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menubar.addAction(self.menuFile.menuAction())
        self.ipAddressLabel.setBuddy(self.ipAddress)
        self.pluginsLabel.setBuddy(self.plugins)

        self.retranslateUi(MainWindow)
        self.pages.setCurrentIndex(1)
        QtCore.QObject.connect(self.pageSelector, QtCore.SIGNAL("currentRowChanged(int)"), self.pages.setCurrentIndex)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Stabilizer", None, QtGui.QApplication.UnicodeUTF8))
        __sortingEnabled = self.pageSelector.isSortingEnabled()
        self.pageSelector.setSortingEnabled(False)
        self.pageSelector.item(0).setText(QtGui.QApplication.translate("MainWindow", "Connections", None, QtGui.QApplication.UnicodeUTF8))
        self.pageSelector.item(1).setText(QtGui.QApplication.translate("MainWindow", "Convergence", None, QtGui.QApplication.UnicodeUTF8))
        self.pageSelector.item(2).setText(QtGui.QApplication.translate("MainWindow", "Instruments", None, QtGui.QApplication.UnicodeUTF8))
        self.pageSelector.item(3).setText(QtGui.QApplication.translate("MainWindow", "Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.pageSelector.setSortingEnabled(__sortingEnabled)
        self.connectionsLabel.setText(QtGui.QApplication.translate("MainWindow", "Currently detected connections", None, QtGui.QApplication.UnicodeUTF8))
        self.worldStateLabel.setText(QtGui.QApplication.translate("MainWindow", "World state", None, QtGui.QApplication.UnicodeUTF8))
        self.convergedStateLabel.setText(QtGui.QApplication.translate("MainWindow", "Converged state", None, QtGui.QApplication.UnicodeUTF8))
        self.instrumentsLabel.setText(QtGui.QApplication.translate("MainWindow", "Currently connected instruments", None, QtGui.QApplication.UnicodeUTF8))
        self.ipAddressLabel.setText(QtGui.QApplication.translate("MainWindow", "IP Address", None, QtGui.QApplication.UnicodeUTF8))
        self.ipAddress.setText(QtGui.QApplication.translate("MainWindow", "127.0.0.1", None, QtGui.QApplication.UnicodeUTF8))
        self.pluginsLabel.setText(QtGui.QApplication.translate("MainWindow", "Loaded plugins", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setText(QtGui.QApplication.translate("MainWindow", "Refresh", None, QtGui.QApplication.UnicodeUTF8))
        self.logIncomingMessagesCheckbox.setText(QtGui.QApplication.translate("MainWindow", "Log incoming messages", None, QtGui.QApplication.UnicodeUTF8))
        self.logOutgoingMessagesCheckbox.setText(QtGui.QApplication.translate("MainWindow", "Log outgoing messages", None, QtGui.QApplication.UnicodeUTF8))
        self.logLabel.setText(QtGui.QApplication.translate("MainWindow", "Log", None, QtGui.QApplication.UnicodeUTF8))
        self.enableInputCheckbox.setText(QtGui.QApplication.translate("MainWindow", "Listen for input", None, QtGui.QApplication.UnicodeUTF8))
        self.calculateConvergenceCheckbox.setText(QtGui.QApplication.translate("MainWindow", "Calculate convergence", None, QtGui.QApplication.UnicodeUTF8))
        self.enableOutputCheckbox.setText(QtGui.QApplication.translate("MainWindow", "Send output", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit.setText(QtGui.QApplication.translate("MainWindow", "Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave_log.setText(QtGui.QApplication.translate("MainWindow", "Save log", None, QtGui.QApplication.UnicodeUTF8))

